# Generated by Django 4.2 on 2023-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_info',
            field=models.TextField(default='Информация скоро появится'),
        ),
        migrations.AddField(
            model_name='author',
            name='img_path',
            field=models.TextField(default='none'),
        ),
    ]
