# Generated by Django 4.2 on 2023-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0004_alter_author_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
