# Generated by Django 4.2 on 2023-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize_song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognize_song',
            name='data_song',
            field=models.TextField(),
        ),
    ]
